// src/Components/Parallax/parallax.jsx
import './parallax.css'
const Parallax = ({data}) => {
    return (
            <>
                {
                    data.map((d, id) => {
                        const {img, text, position} = d
                        return <a key={`parallax-${id}`} href={`/shop/${text}`}>
                            <div className='parallax' style={{backgroundImage: `url(${img})`, backgroundPosition: position}} >
                                <div className="content-container">
                                    <p>{text}</p>
                                    {/*<img data-name={text} onClick={expandSection} src={plusSVG} alt=""/>*/}
                                </div>
                            </div>
                        </a>
                    })
                }
            </>


    )
}
export default Parallax

// src/components/parallax/parallax.vue
<template>
  <div>
    <a
        v-for="(d, id) in data"
        :key="`parallax-${id}`"
        :href="`/shop/${d.text}`"
    >
      <div
          class="parallax"
          :style="{ backgroundImage: `url(${d.img})`, backgroundPosition: d.position }"
      >
        <div class="content-container">
          <p>{{ d.text }}</p>
          <!-- <img :data-name="d.text" @click="expandSection" src="plusSVG" alt=""/> -->
        </div>
      </div>
    </a>
  </div>
</template>

<script>
export default {
  props: {
    data: {
      type: Array,
      required: true
    }
  },
  methods: {
    // expandSection() {
    //   // Implement functionality for expandSection
    // }
  }
};
</script>

<style>
@import './parallax.css';
</style>
