// src/app/button/button.component.ts
import { Component, Input } from '@angular/core';
import {NgStyle} from '@angular/common';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  standalone: true,
  imports: [
    NgStyle
  ],
  styleUrls: ['./button.component.css']
})
export class ButtonComponent {
  @Input() text: string = '';
  @Input() clickHandler: () => void = () => {};  // Default empty function
  @Input() color: string = 'black'; // Default color
  @Input() fontSize: string = '1em'; // Default font size
  @Input() dividers: boolean = false; // Default no divider
}

<button class="button-container" (click)="clickHandler()" [ngStyle]="{'color': color, 'border': '1px solid ' + color, 'font-size': fontSize}">
  <div *ngIf="dividers" class="divider-top"></div>
  {{ text }}
</button>

// src/components/button/button.vue
<template>
  <button
      class="button-container"
      @click="clickHandler"
      :style="buttonStyles"
  >
    <div v-if="dividers" class="divider-top"></div>
    {{ text }}
  </button>
</template>

<script>
export default {
  props: {
    text: {
      type: String,
      required: true
    },
    clickHandler: {
      type: Function,
      required: true
    },
    color: {
      type: String,
      required: true
    },
    fontSize: {
      type: String,
      required: true
    },
    dividers: {
      type: Boolean,
      default: false
    }
  },
  computed: {
    buttonStyles() {
      return {
        color: this.color,
        border: `1px solid ${this.color}`,
        fontSize: this.fontSize
      };
    }
  }
};
</script>

<style>
@import './button.css';
</style>
